import { createHash } from "crypto";

/**
 * Sticky Provider Router — Account-to-Session Affinity
 * 
 * Binds conversations with active Gemini thought signatures to specific provider accounts.
 * Once a tool-call loop starts, that conversation "belongs" to the account that generated
 * the signature. This maintains cryptographic integrity (lock-key match) across turns.
 * 
 * The Lock-and-Key Analogy:
 * - Signature = Lock: generated by specific account (e.g., Account A)
 * - Account = Key: only Account A can unlock its own signatures
 * - Rotation breaks it: if we switch to Account B mid-conversation, Account B's key
 *   can't unlock Account A's signature → 400 error
 * 
 * Session Affinity ensures:
 * 1. Once tool-call loop starts, conversation locked to that account
 * 2. Rotation still works across different conversations
 * 3. Affinity expires with signature TTL (24hr)
 */

interface SessionBinding {
  providerId: string;
  accountEmail: string;
  boundAt: number;
  expiresAt: number;
}

// Session → Provider binding cache (in-memory)
// Stores which account is bound to which conversation
const sessionProviders = new Map<string, SessionBinding>();

/**
 * Extract stable session ID from request body
 * Hash first N messages to create stable session ID for conversation tracking
 */
export function extractSessionId(body: any): string {
  const messages = body.messages || [];
  const sessionMessages = messages.slice(0, 5); // first 5 messages
  return createHash("sha256")
    .update(JSON.stringify(sessionMessages))
    .digest("hex")
    .slice(0, 16);
}

/**
 * Establish Account-to-Session Affinity
 * Lock this conversation to a specific provider account for the signature TTL duration (24hr)
 * Called when thinking+tools enabled and conversation starts
 */
export function bindSessionToProvider(
  sessionId: string,
  providerId: string,
  accountEmail: string
): void {
  const now = Date.now();
  const ttlMs = 1000 * 60 * 60 * 24; // 24 hours to match signature TTL

  sessionProviders.set(sessionId, {
    providerId,
    accountEmail,
    boundAt: now,
    expiresAt: now + ttlMs,
  });

  console.log(
    `[Sticky Session] Bound session ${sessionId} to account ${accountEmail}`
  );
}

/**
 * Get bound provider for a session
 * Returns the account ID ("key") locked to this conversation, or null if no affinity
 * Auto-prunes expired bindings
 */
export function getSessionProvider(sessionId: string): string | null {
  const binding = sessionProviders.get(sessionId);
  if (!binding) return null;

  // Binding expired — release it
  if (binding.expiresAt <= Date.now()) {
    sessionProviders.delete(sessionId);
    return null;
  }

  return binding.providerId;
}

/**
 * Release session affinity
 * Called when task finished or signatures expired
 * Allows rotation again for subsequent requests
 */
export function releaseSession(sessionId: string): void {
  if (sessionProviders.has(sessionId)) {
    sessionProviders.delete(sessionId);
    console.log(`[Sticky Session] Released session ${sessionId}`);
  }
}

/**
 * Check if request contains active tool calls that need affinity
 * If yes, session must maintain sticky routing (no account rotation)
 */
export function hasActiveSignatures(body: any): boolean {
  const messages = body.messages || [];
  for (const msg of messages) {
    if (msg.role === "assistant" && msg.tool_calls) {
      return true; // Has tool calls, needs sticky routing
    }
  }
  return false;
}

/**
 * Get current session binding info (for debugging/logging)
 */
export function getSessionBindingInfo(sessionId: string): SessionBinding | null {
  const binding = sessionProviders.get(sessionId);
  if (!binding) return null;

  if (binding.expiresAt <= Date.now()) {
    sessionProviders.delete(sessionId);
    return null;
  }

  return binding;
}

/**
 * Cleanup expired bindings (called periodically to prevent memory bloat)
 */
export function pruneExpiredBindings(): number {
  const now = Date.now();
  let prunedCount = 0;

  for (const [sessionId, binding] of sessionProviders.entries()) {
    if (binding.expiresAt <= now) {
      sessionProviders.delete(sessionId);
      prunedCount++;
    }
  }

  if (prunedCount > 0) {
    console.log(`[Sticky Session] Pruned ${prunedCount} expired session bindings`);
  }

  return prunedCount;
}

/**
 * Get count of active session bindings (for monitoring)
 */
export function getActiveSessionCount(): number {
  const now = Date.now();
  let count = 0;

  for (const binding of sessionProviders.values()) {
    if (binding.expiresAt > now) {
      count++;
    }
  }

  return count;
}
